env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - "prettier"
  - "prettier/@typescript-eslint"
  - "prettier/react"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": ["error", {
    "vars": "all",
    "args": "after-used",
    "ignoreRestSiblings": false
  }]
}
