env:
  browser: true
  es2021: true
# extends:
  # -  "some-other-config-you-use"
  # -  "plugin:prettier/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  # 構文チェックルールをoffに
  "no-unused-vars": "off",
}
